### ISSUE TITLE
cmd run script issue after running setup (openAI resources instead of pure azure)

### ISSUE THREAD

**Issue by jcf0419** [microsoft/kernel-memory#172] opened 2023-11-27 13:23 UTC
Hello I'm attempting to use the setup and run .cmd files in the service folder. My configuration is using OpenAI instead of azure. 
On running "run" in command prompt it outputs and error about a blank "deploymentName" which I understand as an azure only required environment variable. I looked through the appsettings.Development.json produced when running setup and don't see it there and I wouldn't expect this would be needed to run.

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.94
Unhandled exception. System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'deploymentName')
   at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.AzureOpenAIClientBase..ctor(String deploymentName, String endpoint, TokenCredential credential, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.AzureOpenAITextEmbeddingGeneration..ctor(String deploymentName, String endpoint, TokenCredential credential, String modelId, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.KernelMemory.DependencyInjection.<>c__DisplayClass0_0.<AddAzureOpenAIEmbeddingGeneration>b__0(IServiceProvider serviceProvider) in C:\Users\jcf04\Desktop\kernel-memory\service\Core\AI\AzureOpenAI\DependencyInjection.cs:line 38
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.KernelMemory.KernelMemoryBuilder.FromConfiguration(KernelMemoryConfig config, IConfiguration servicesConfiguration) in C:\Users\jcf04\Desktop\kernel-memory\service\Core\KernelMemoryBuilder.cs:line 285
   at Microsoft.KernelMemory.KernelMemoryBuilder.FromAppSettings(String settingsDirectory) in C:\Users\jcf04\Desktop\kernel-memory\service\Core\KernelMemoryBuilder.cs:line 198
   at Program.<Main>$(String[] args) in C:\Users\jcf04\Desktop\kernel-memory\service\Service\Program.cs:line 80
```

**Comment by jcf0419** [comment] 2023-11-29 00:24
Just an update .. apparently only an issue when I run the run.cmd file in the Services directory.

with the follwing launch.json configuration in vscode.. it works.. 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/service/Service/bin/Debug/net7.0/Microsoft.KernelMemory.ServiceAssembly.dll",
            "args": [],
            "cwd": "${workspaceFolder}/service/Service",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```

**Comment by dluc** [comment] 2023-11-30 05:31
hi @jcf0419 we just merged some changes touching configuration and starting options. hopefully those might help. You could also try running `dotnet run setup` to generate a configuration file

**Comment by dluc** [comment] 2023-12-06 08:46
Please let us know if the issue is still present, we can reopen the issue. Thanks

**Closed by dluc** 2023-12-06 08:46 UTC
Labels: question
