### ISSUE TITLE
[Bug] Connection pool not released after Postgres query

### ISSUE THREAD

**Issue by xuzeyu91** [microsoft/kernel-memory#679] opened 2024-06-26 13:57 UTC
### Context / Scenario

```
await memoryDb.GetListAsync(KmsConstantcs.KmsIndex, filters: new List<MemoryFilter>() { new MemoryFilter().ByDocument(fileId) }, limit: int.MaxValue).ToListAsync().ConfigureAwait(false);
```
I often encounter anomalies such as sorry, too many clients are already ready when querying document slices. I have observed that each query adds a new link

```
SELECT count(*) FROM pg_stat_activity;
```
I have found that every query adds new links and they are not dispose. Frequent queries will cause my Postgres connection pool to fill up

### What happened?

too many clients are already ready

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

I use kernel-memory to connect to Postgres

### Relevant log output

```shell
too many clients are already ready
```

**Comment by xuzeyu91** [comment] 2024-06-26 14:07
https://github.com/microsoft/kernel-memory/blob/3d34260ae513af48030da9a56aa50b8e0162c6f8/extensions/Postgres/Postgres/Internals/PostgresDbClient.cs#L529

I'm not sure if there's a problem here

**Comment by xuzeyu91** [comment] 2024-06-27 08:47
```
 _memoryDbs = memory.Orchestrator.GetMemoryDbs();
 foreach (var memoryDb in _memoryDbs)
 {
     var items = await memoryDb.GetListAsync(KmsConstantcs.KmsIndex, filters: new List<MemoryFilter>() { new MemoryFilter().ByDocument(fileId) }, limit: int.MaxValue).ToListAsync().ConfigureAwait(false);
 }
```
This is my code, I need to retrieve the slice data from the document, which will cause the number of connections to increase continuously

**Comment by marcominerva** [comment] 2024-07-02 08:26
@dluc, could it be related to the fact that `PostgresMemory` is registered as singleton? `PostgresMemory` in turns creates a `PostgresDbClient`. So, even if both `PostgresMemory` and `PostgresDbClient` implements `IDisposable`, the `Dispose` methods are never called.

In particular, I see that `PostgresDbClient` contains an `NpgsqlDataSource` object that is created in the constructor but never disposed:
https://github.com/microsoft/kernel-memory/blob/3d34260ae513af48030da9a56aa50b8e0162c6f8/extensions/Postgres/Postgres/Internals/PostgresDbClient.cs#L31

**Comment by dluc** [comment] 2024-07-27 10:39
Each connection is opened and released using this pattern:

```csharp
NpgsqlConnection connection = await this.ConnectAsync(cancellationToken);
await using (connection)
{
    // do some work
    // return result
}
```

`DisposeAsync()` calls `CloseAsync()` so everything should work. I've changed the pattern in https://github.com/microsoft/kernel-memory/pull/720 (see below) to call `CloseAsync` explicitly, but I'm not convinced this will help. 

The problem reported might be caused by a high number of transactions, in which case I would check Postgres configuration to scale accordingly.


```csharp
NpgsqlConnection connection = await this.ConnectAsync(cancellationToken);
await using (connection)
{
    try 
        // do some work
        // return result
    finally
        // disconnect
}
```

**Comment by dluc** [comment] 2024-08-03 07:57
@xuzeyu91 is the problem still occurring with the latest code?

**Comment by xuzeyu91** [comment] 2024-08-05 14:55
> @xuzeyu91 is the problem still occurring with the latest code?

I am using version 0.70.240803.1, but this issue still persists

**Comment by dluc** [comment] 2024-08-28 04:37
The fact that the client is a singleton should protect from too many connections. If someone has the time to investigate further that could help. For instance, log every new connection, monitor if connections are actually closed, check PG configuration to see what the limit is, etc.

**Comment by dluc** [comment] 2024-09-07 17:55
This should be fixed with the latest release, otherwise please let us know.

**Closed by dluc** 2024-09-07 17:55 UTC
Labels: bug, help needed

**Comment by marcominerva** [comment] 2024-10-05 10:41
Hi @xuzeyu91,

After further consideration (see https://github.com/microsoft/kernel-memory/issues/789 and the related issue on the official Npgsql repository at https://github.com/npgsql/npgsql/issues/5862#issuecomment-2391068719), we reverted to the original connection pool handling, that is the recommended approach.

In you scenario, when connection pool not released is a concern, the suggestion is adding `Pooling=false` in the connection string.
