### ISSUE TITLE
warning NU1608: Detected package version outside of dependency constraint: ClosedXML 0.102.2 requires DocumentFormat.OpenXml (>= 2.16.0 && < 3.0.0) but version DocumentFormat.OpenXml 3.1.0 was resolved.

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/kernel-memory#725] opened 2024-08-01 07:06 UTC
### Context / Scenario

My project makes use of both the following dependencies:

```xml
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.0" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.69.240727.1" />
```

### What happened?

When compiling with `dotnet build`, this leads to a warning:

> warning NU1608: Detected package version outside of dependency constraint: ClosedXML 0.102.2 requires DocumentFormat.OpenXml (>= 2.16.0 && < 3.0.0) but version DocumentFormat.OpenXml 3.1.0 was resolved.

Is it related to this perhaps? https://github.com/microsoft/kernel-memory/blob/6c092a930668fece582ac1cfc39c8e3040188f0c/Directory.Packages.props#L59

I notice a new version has recently shipped which may resolve it? https://github.com/microsoft/kernel-memory/issues/265

See also:
- https://github.com/ClosedXML/ClosedXML/issues/2315
- https://github.com/microsoft/kernel-memory/issues/265

### Importance

a fix would make my life easier

### Platform, Language, Versions

.NET 8, C# 0.69.240727.1

### Relevant log output

```shell
warning NU1608: Detected package version outside of dependency constraint: ClosedXML 0.102.2 requires DocumentFormat.OpenXml (>= 2.16.0 && < 3.0.0) but version DocumentFormat.OpenXml 3.1.0 was resolved.
```

**Comment by marcominerva** [comment] 2024-08-01 07:20
Yes, the problem is related to **ClosedXML** that is currently incompatible with **DocumentFormat.Xml v3.0**. Unless you explicitly need features that are available only in the last version, you can safely remove the explictly dependency.

**Comment by johnnyreilly** [comment] 2024-08-01 07:26
We explicitly use `DocumentFormat.OpenXml` to produce Word documents and so we do explicitly require that dependency.  

Looking at the `ClosedXML.csproj` it looks like it supports 3:

https://github.com/ClosedXML/ClosedXML/blob/bec5851f89af7920d133d130425ec4cac038dc5b/ClosedXML/ClosedXML.csproj#L35

```xml
<PackageReference Include="DocumentFormat.OpenXml" Version="[3.0.1,4.0.0)" />
```

I'm wondering if the release from a couple of weeks ago includes this: https://github.com/ClosedXML/ClosedXML/releases/tag/0.102.3

**Comment by marcominerva** [comment] 2024-08-01 07:43
**ClosedXML** version 102.3 still requires **DocumentFormat.Xml v2**: https://www.nuget.org/packages/ClosedXML/0.102.3#dependencies-body-tab.

The support for **v3** has been merged in the `main` branch, but it hasn't been released on NuGet yet. It should be included in the next 104 version, that hasn't a release date yet: https://github.com/ClosedXML/ClosedXML/discussions/2367.

If you remove the explicit dependency, you can still use **DocumentFormat.Xml v2** in your project, because it is inherited when you add the Kernel Memory dependency.

**Comment by johnnyreilly** [comment] 2024-08-01 07:56
I didn't realise that you could use https://www.nuget.org/packages/ClosedXML/0.102.3#dependencies-body-tab - TIL!

I think even when the new version ships there's still going to be an issue. Have raised this to track: https://github.com/ClosedXML/ClosedXML/issues/2379

**Comment by marcominerva** [comment] 2024-08-01 07:58
As soon as ClosedXML 104 is released, Kernel Memory will be updated to use the new version.

**Comment by dluc** [comment] 2024-09-07 17:46
I did one more test with the latest release, and `ClosedXML` nugets are still incompatible with `DocumentFormat.OpenXml` v3, breaking Excel docs import. 

The code in `ClosedXML` main branch works fine, but for some reason they stopped releasing nugets last year.

* ClosedXML `0.102.3` + OpenXml to 3.1.0 => **Exception**
* ClosedXML `0.103.0-beta`  + OpenXml to 3.1.0 => **Exception**
* ClosedXML `0.104.0-preview2` + OpenXml to 3.1.0 => **Exception**
* ClosedXML `ef915a5db05a0a57499e34e418096228f097ffee` + OpenXml to 3.1.0 => **OK**

Exception:
```
Unhandled exception. System.MissingMethodException: Method not found: 'DocumentFormat.OpenXml.OpenXmlElementList DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()'.
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
```

**Comment by dluc** [comment] 2024-09-07 17:53
If your project needs `DocumentFormat.OpenXml v3`, here's a couple of options:

* isolate KM from the rest of your code base, running KM as a web service
* build everything from source, patching KM to use `ClosedXML` source code from their main branch, replacing the `ClosedXML` nuget dependency from `Core.csproj` with a project reference.

**Closed by dluc** 2024-09-07 17:53 UTC
Labels: feature request

**Comment by dluc** [comment] 2024-09-19 18:00
Fixed in https://github.com/microsoft/kernel-memory/pull/792
